server:
  port: 56720
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.5.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  application:
    name: jwxt-student #指定服务名


  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-location: classpath:com/kytms/*/mapper/*.xml

ftp:
  host: 192.168.5.210
  port: 22
  username: root
  password: dmcn@123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:56798/eureka/,http://localhost:56799/eureka/
  instance:
    prefer-ip-address: true
    instance-id: student
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true



#断路器
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true #启动断路器
        requestVolumeThreshold: 1 #请求数到达后次啊计算
        sleepWindowInMilliseconds: 10000 #休眠时间
        errorThresholdPercentage: 1 #错误率
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #设置请求超时时间（默认是一秒） 超时后会走后备方法

management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  authorization:
    key-name: token
