server:
  port: 56798
spring:
  application:
    name: eureka-test01 #当前应用的名字（应用注册后的应用名）

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:mysql://192.168.5.240:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

eureka:
  instance:
    hostname: server1 #eureka地址
    prefer-ip-address: true #设置微服务调用地址IP优先 (默认为false)
    instance-id: serve01 #注册后的实例id
    lease-renewal-interval-in-seconds: 30 #心跳时间  即服务续约间隔时间
    lease-expiration-duration-in-seconds: 90 #发呆时间.即服务续约到期时间(缺省90)

  client:
    fetch-registry: true #是否拉取服务表
    register-with-eureka: false #是否注册进入eureka（当前的eureka不注册进入注册中心）
    service-url:
      defaultZone: http://localhost:56799/eureka/ #默认注册地址，当使用security时要加入对应的用户名和密码http://g01:123456@server2:8762/eureka/    其他端使用方法一致

  server:
    enable-self-preservation: false #Eureka的自我保护机制关闭，红字提醒（生产环境不推荐关闭）
    eviction-interval-timer-in-ms: 60000 # 默认为60 * 1000ms (一分钟)
